name: Build & Publish Cloudflare Worker

on:
  push:
    branches: [ "main" ]
    
env:
  NODE_VERSION: 16.17

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/boatswain
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm ci
      run: npm ci

    - name: Build & Publish
      run: npm run deploy
      env: 
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
